### ISSUE TITLE
better / new ROSTER

### ISSUE THREAD

**Issue by kneegrew** [Neefay/BromA-Framework-A3-Addon#16]
The roster does not seem to update and might need an update.

**Comment by Coryf88** [comment]
![20170801121200_1](https://user-images.githubusercontent.com/204475/28837544-c23d05e8-76b2-11e7-9da7-09bc029241d3.jpg) Currently updates every second. Should anything be changed/added/removed?

**Comment by Neefay** [comment]
@Coryf88 This is really great, I like it a lot and imo the icons do make it more better. I think just a bit of a margin between the groups would be good lest it gets too cluttered.

**Comment by badkneegrow** [comment]
@Coryf88 Ranks don't really matter. This looks good, as long as it updates.

**Comment by Neefay** [comment]
@badkneegrow Is it even possible to have it updating though? Last time I checked you can't delete or edit a Diary entry.

**Comment by Coryf88** [comment]
@Neefay Indeed, it unluckily isn't possible to edit nor delete a Diary entry. I've used a workaround that adds a StructuredText control in the Diary control's group, which is then displayed/updated when "Team Roster" is selected.

**Comment by Neefay** [comment]
@Coryf88 That is extremely fucking ninja, I can't wait to see it implemented.
