### ISSUE TITLE
Plugin: Loading Screen

### ISSUE THREAD

**Issue by Coryf88** [Neefay/BromA-Framework-A3-Addon#38]
Delays vision based on FPS, _holsters_ weapon, and delays [Intros](https://github.com/Neefay/BromA-Framework-A3-Addon/tree/master/plugins/intros) plugin.

- [x] Use [`uiSleep`](https://community.bistudio.com/wiki/uiSleep) instead of [`sleep`](https://community.bistudio.com/wiki/sleep) [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/loading_screen/functions/fn_postinit.sqf#L21)]

- [x] ~Use [startLoadingScreen](https://community.bistudio.com/wiki/startLoadingScreen) instead of [`titleText`](https://community.bistudio.com/wiki/titleText)~
Disables simulation, which could cause issues.

- [x] Remove `SwitchWeapon` [`action`](https://community.bistudio.com/wiki/action) and have it done by the Engine. [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/loading_screen/functions/fn_postinit.sqf#L15)]
[Function](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/engine/api/fn_weaponAway.sqf) for it is already in the Engine, but never used.
A unit could potentially have a muzzle index of `99`, change to `-1`

- [x] Private `_loadingScreen`, `_reqFPS`, `_timeout`

- [x] Use [`floor`](https://community.bistudio.com/wiki/floor) instead of [`round`](https://community.bistudio.com/wiki/round) [[1](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/loading_screen/functions/fn_postinit.sqf#L17), [2](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/loading_screen/functions/fn_postinit.sqf#L22)]

- [x] Delete [includes/settings.sqf](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/loading_screen/functions/includes/settings.sqf) and move contents into [fn_postinit.sqf](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/loading_screen/functions/fn_postinit.sqf#L13)

- [x] Synchronize the loading screen for all players

- [x] ~Look into another metric for loading, instead of FPS~
Unluckily, I'm unable to find any alternative.

**Comment by badkneegrow** [comment]
https://community.bistudio.com/wiki/startLoadingScreen

**Comment by Neefay** [comment]
> Synchronize the loading screen for all players

You sure this is a good idea? I see people getting pissed off at each other for either lagging or crashing, or at the very least starting a witch hunt because they think someone caused their game to crash.

**Comment by Coryf88** [comment]
Yes, such a change would force player's to stand still (Armastock) at the start until the metric is met for the server/players, though a timeout should still be included.
