### ISSUE TITLE
Plugin: Respawn System

### ISSUE THREAD

**Issue by Coryf88** [Neefay/BromA-Framework-A3-Addon#39]
- [x] Replace 'player' with '_unit' [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/respawn_system/functions/fn_removeFromMission.sqf)]
- [x] Move publicVariable outside of loop [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/respawn_system/functions/fn_callRespawn.sqf#L54)] [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/respawn_system/functions/fn_callRespawnSide.sqf#L48)]
- [x] Potential issues if player with specified name doesn't exist [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/respawn_system/functions/fn_callRespawn.sqf#L42)]
- [x] Break out of loop if there isn't any more dead players [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/respawn_system/functions/fn_callRespawn.sqf#L49)] [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/respawn_system/functions/fn_callRespawnSide.sqf#L51)]
- [x] Less players than requested are respawned [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/respawn_system/functions/fn_callRespawn.sqf#L50)]
E.g. `[4] spawn BRM_FMK_RespawnSystem_fnc_callRespawn;`
Dead: Respawned
1-2: 1
3-4: 2
5-6: 3
7+: 4
- [x] Amount of lives a player has is reset to default on respawn [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/respawn_system/functions/fn_callRespawn.sqf#L38)] [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/respawn_system/functions/fn_callRespawnSide.sqf#L39)]

**Comment by badkneegrow** [comment]
Respawning / dying might make the player be recreated where he dies before he is moved to spectator.
Test this with heavy load and kill players and see if another player can see them "reappear" for a frame where he died
