### ISSUE TITLE
Plugin: AGM

### ISSUE THREAD

**Issue by Coryf88** [Neefay/BromA-Framework-A3-Addon#43]
- [ ] Unused global variable [agm_settings_PreventInstaDeath](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/agm_plugin/functions/includes/settings.sqf#L9)
Most likely remnants of switching to [Mission Params](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/agm_plugin/functions/fn_setParams.sqf#L11)
- [ ] Unused global variable [agm_settings_SingleBandage](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/agm_plugin/functions/includes/settings.sqf#L11)
Most likely remnants of switching to [Mission Params](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/agm_plugin/functions/fn_setParams.sqf#L21)
- [ ] AGM is discontinued. https://github.com/KoffeinFlummi/AGM#-this-mod-is-discontinued-please-move-to-ace3

**Comment by Neefay** [comment]
This plugin is deprecated as deprecated can be. Who cares.
