### ISSUE TITLE
Plugin: AO Limit

### ISSUE THREAD

**Issue by Coryf88** [Neefay/BromA-Framework-A3-Addon#44]
- [ ] Plugin will stop functioning after player has died. [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/ao_limit/functions/fn_postinit.sqf#L22)]
- [x] Test if [`left_ao_do`](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/ao_limit/functions/includes/settings.sqf#L5) can be modified in mission.
- [ ] Disable functionality if `mission_game_mode != "coop"`

**Comment by Neefay** [comment]
@Coryf88 , could you clarify on:

> Disable functionality if mission_game_mode != "coop"

Is there any other functionality for TvTs that stops people from leaving the AO? Because if there isn't, that's a very much desired functionality.

**Comment by Coryf88** [comment]
I'm not sure why I added that.
