### ISSUE TITLE
Plugin: Chair Plugin

### ISSUE THREAD

**Issue by Coryf88** [Neefay/BromA-Framework-A3-Addon#46]
_My eyes... they bleed_

- [ ] Plugin has been deprecated for about a [year](https://github.com/Neefay/BromA-A3-Framework-Mark3/commit/3daff0d29c62c495c1cbaf85aef8bcbd2e7485b3), remove it.

ACE3's [sitting](https://ace3mod.com/wiki/featurex/sitting.html) can be used instead.

**Comment by Neefay** [comment]
HEY MAN IT WORKED ALRIGHT LEAVE ME ALONE
