### ISSUE TITLE
Plugin: Commander Lock

### ISSUE THREAD

**Issue by Coryf88** [Neefay/BromA-Framework-A3-Addon#48]
- [ ] Global variables that should be made local
`co_lock_text_select`
`co_lock_text_start`
`co_lock_text_started` (_Used by Rhea_)
`alertColor`
`removeBulletsEH`
- [ ] Needed global variables should be renamed. E.g. `co_lock_tvt_mode` to `brm_fmk_co_lock_tvt_mode` or something similiar.
- [ ] Remove unused `player_co_locked` variable
- [ ] Enforce restrictions also for the commander
- [ ] Add additional restrictions, incuding throwing grenades and using explosives

**Comment by Neefay** [comment]
I won't be able to rename global variables such as "co_lock_tvt_mode" due to retroactive compat. with older missions. Whatever solutions I came up with were just a mess of spaghetti code for what in my opinion wouldn't be THAT beneficial.

**Comment by Neefay** [comment]
>Enforce restrictions also for the commander
Also going against that, the Commander should be able to do as he pleases.
