### ISSUE TITLE
Plugin: F Casualties Cap

### ISSUE THREAD

**Issue by Coryf88** [Neefay/BromA-Framework-A3-Addon#51]
- [x] Make `casBLU`, `casOP`, and `casIND` local variables [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/f_casualties_cap/functions/fn_postinit.sqf#L12)]

- [x] Merge forEach [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/f_casualties_cap/functions/fn_CasualtiesCapCheck.sqf#L31)]
- [x] Comment says 10, code says 5 [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/f_casualties_cap/functions/fn_CasualtiesCapCheck.sqf#L56)]
- [x] `array `[`select`](https://community.bistudio.com/wiki/select)` expression` [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/f_casualties_cap/functions/fn_CasualtiesCapCheck.sqf#L65)]
- [x] [`while`](https://community.bistudio.com/wiki/while) [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/f_casualties_cap/functions/fn_CasualtiesCapCheck.sqf#L93)]

**Comment by Neefay** [comment]
@Coryf88 Once again I'm stuck by this one, what did you have in mind for:

> ` array select expression`

**Comment by Coryf88** [comment]
`_grps = _grpstemp select { !isNull _x && {({alive _x} count (units _x)) >= 1 }};`
