### ISSUE TITLE
Plugin: F Evade Escape

### ISSUE THREAD

**Issue by Coryf88** [Neefay/BromA-Framework-A3-Addon#52]
- [x] Remove [this](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/f_evade_escape/functions/fn_reachObject.sqf#L20)
- [x] `condition `[`count`](https://community.bistudio.com/wiki/count)` array` [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/f_evade_escape/functions/fn_reachObject.sqf#L27)]
- [x] Should also stop the while loop when extracted [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/f_evade_escape/functions/fn_reachObject.sqf#L30)]
- [x] `_safe` check isn't limited to [`alive`](https://community.bistudio.com/wiki/alive) players [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/f_evade_escape/functions/fn_reachObject.sqf#L27)]
- [x] Make [`_code`](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/f_evade_escape/functions/fn_reachObject.sqf#L13) and [`_y`](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/f_evade_escape/functions/fn_reachObject.sqf#L23) a private variable.

**Comment by Neefay** [comment]
>`condition count array`

@Coryf88 Could you elaborate on what you meant by this?

**Comment by Coryf88** [comment]
`{ _x distance _y < _safeDistance } count units _x`
