### ISSUE TITLE
Plugin: Headless Client

### ISSUE THREAD

**Issue by Coryf88** [Neefay/BromA-Framework-A3-Addon#54]
- [x] Remove `HeadlessController` [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/headless_client/functions/fn_postinit.sqf#L21)]
+DAC Plugin changed from `HeadlessController` to `mission_AI_controller` [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/dac_plugin/functions/fn_DACZone.sqf#2)]

- [ ] Merge if statements [[1](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/headless_client/functions/fn_postinit.sqf#L2), [2](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/headless_client/functions/fn_postinit.sqf#L3), [3](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/headless_client/functions/fn_postinit.sqf#L5), [4](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/headless_client/functions/fn_postinit.sqf#L6)]

- [x] Analyze [core_functions.sqf](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/headless_client/functions/includes/core_functions.sqf)

**Comment by Neefay** [comment]
Core functions are obsolete, especially now that we use WHM.

**Comment by Neefay** [comment]
The `HeadlessController` variable is also utilized in the DAC addon we've modified years ago. I'll be honest, it's a can of worms I'd rather not fuck with.

**Comment by Coryf88** [comment]
I don't find any usage of `HeadlessController` or `mission_AI_controller` in DAC source.

**Comment by Neefay** [comment]
It's been done.

**Comment by Neefay** [comment]
@Coryf88 , I'm gonna have to once again rely on your coding skills:

> [ ] Merge if statements [1, 2, 3, 4]

My problem is that these statements took a long goddamn ass time to test and getting them right was just hell back when I was trying to figure out HC, hence, I'm basically scared shitless of messing something up.

**Comment by Coryf88** [comment]
```sqf
mission_AI_controller = if (mission_enable_hc) then { !isServer && !hasInterface } else { isServer };
if (mission_AI_controller) then {
	mission_HC_enabled = true;
	publicVariable "mission_HC_enabled";
};
```

**Comment by Neefay** [comment]
I seriously admire your coding skills. You rock, dude.
