### ISSUE TITLE
Plugin: Setup Zone

### ISSUE THREAD

**Issue by Coryf88** [Neefay/BromA-Framework-A3-Addon#65]
- [x] `!(str _x == "<NULL-object>")` to `!(isNull _x)` [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/setup_zone/functions/fn_postinit.sqf#L8)]

- [x] Execute remaining code only if [`hasInterface`](https://community.bistudio.com/wiki/hasInterface) [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/setup_zone/functions/fn_postinit.sqf#L17)]

- [x] Call `BRM_FMK_SetupZone_fnc_setupZone` only for the player's side. [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/setup_zone/functions/fn_postinit.sqf#L27)]

- [x] Move block into [fn_postinit.sqf](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/setup_zone/functions/fn_postinit.sqf#L12) and modify to affect all sides [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/setup_zone/functions/fn_setupZone.sqf#L10)]

- [x] Delete [includes/settings.sqf](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/setup_zone/functions/includes/settings.sqf) and move contents into [fn_postinit.sqf](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/setup_zone/functions/fn_postinit.sqf#L11)

- [x] Rename global variable `setup_sides` to something like `brmFmk_setupZone_sides`

- [x] Remove global variables `zone1`, `zone2`, and `zone3` [[1](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/setup_zone/functions/fn_postinit.sqf#L27), [2](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/setup_zone/functions/fn_postinit.sqf#L28), [3](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/setup_zone/functions/fn_postinit.sqf#L31)]

- [x] `<=` to `<` [[1](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/setup_zone/functions/fn_setupZone.sqf#L59), [2](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/setup_zone/functions/fn_setupZone.sqf#L65)]

- [x] If `_time` is "minutes", then convert `_time` to minutes (divide `_time` by 60) [[1](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/setup_zone/functions/fn_setupZone.sqf#L59), [2](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/setup_zone/functions/fn_setupZone.sqf#L65)]

**Comment by badkneegrow** [comment]
Spawn protection should probably be a part of the setup zone.
I don't see a reason why they should be two different plugins...

**Comment by Coryf88** [comment]
Spawn protection prevents player's from receiving damage in an area near the spawn location.
Setup zone prevents player's from leaving an area near the spawn location.

They are different plugins because they do different things, the only similarity is the location that they affect.
