### ISSUE TITLE
Team Roster

### ISSUE THREAD

**Issue by badkneegrow** [Neefay/BromA-Framework-A3-Addon#69]
Does not work during briefing

Center it a bit more ? There seems to be too much space on the right side and too little on the left

**Comment by badkneegrow** [comment]
https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/team_roster/functions/fn_roster.sqf#L84

Weird, I think it did not create a pull request, but I either way I updated the roster.

Sleep 1; was keeping it from updating during briefing (no simulation)
Used uiSleep instead.

**Comment by Coryf88** [comment]
I assume you tested your fix?

**Comment by badkneegrow** [comment]
Nope

**Comment by Coryf88** [comment]
Well, it'd probably be a good thing to test fixes before commiting/PRing them. Since, this will not fix Team Roster showing during briefing, though it should fix it updating.
