### ISSUE TITLE
Plugin: TFAR Plugin

### ISSUE THREAD

**Issue by Coryf88** [Neefay/BromA-Framework-A3-Addon#70]
- [ ] Delete [includes/settings.sqf](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/tfar_plugin/functions/includes/settings.sqf) and move contents into [fn_postinit.sqf](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/tfar_plugin/functions/fn_postinit.sqf#L3)

- [ ] Update to support TFAR 1.0 Beta [Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/tfar_plugin/functions/includes/settings.sqf)

- [ ] Merge `if` statements [[1](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/tfar_plugin/functions/fn_aiHearsTFAR.sqf#L5), [2](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/tfar_plugin/functions/fn_aiHearsTFAR.sqf#L6)]

- [ ] Change to use TFAR's "OnSpeak" event [Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/tfar_plugin/functions/fn_aiHearsTFAR.sqf#L21)
[TFAR_fnc_addEventHandler](https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API:-Functions#TFAR_fnc_addEventHandler), handler receives `[_unit, _isSpeaking]` not `[_unit, _volume]`

- [ ] Remove `b_hasRadioCheck` and use `TFAR_fnc_haveSWRadio` directly [Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/tfar_plugin/functions/fn_aiHearsTFAR.sqf#L14)

- [ ] Change `(TF_speak_volume_meters * 2)` to `(TF_speak_volume_meters)` or less [Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/tfar_plugin/functions/fn_aiHearsTFAR.sqf#L29)

- [ ] Use `[_nearAISingle, [player, _revealAmount]] `[`remoteExec`](https://community.bistudio.com/wiki/remoteExec)` ["reveal", _nearAISingle];` [Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/tfar_plugin/functions/fn_aiHearsTFAR.sqf#L82)

- [ ] Could alter the reveal amount, based on how far away the player is [Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/tfar_plugin/functions/fn_aiHearsTFAR.sqf#L43)

- [ ] Remove ` && !(_x knowsAbout player >= 4.0)` [Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/tfar_plugin/functions/fn_aiHearsTFAR.sqf#L35)

- [ ] Add checks for if the player is in an 'isolated' vehicle, spectating, or dead [Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/tfar_plugin/functions/fn_aiHearsTFAR.sqf#L23)
[TFAR_fnc_vehicleIsIsolatedAndInside](https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API:-Functions#TFAR_fnc_vehicleIsIsolatedAndInside)

- [ ] Store `leader (group _nearAISingle)` in a variable and use it for [`findNearestEnemy`](https://community.bistudio.com/wiki/findNearestEnemy) [Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/tfar_plugin/functions/fn_aiHearsTFAR.sqf#L75)

- [ ] Remove `getPos`, can use the unit itself [Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/tfar_plugin/functions/fn_aiHearsTFAR.sqf#L75)

- [ ] Move `_enemyInContact` before the `if` statement, and use `_enemyInContact` in the `if` statement [Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/tfar_plugin/functions/fn_aiHearsTFAR.sqf#L75)

- [ ] [`distanceSqr`](https://community.bistudio.com/wiki/distanceSqr) [Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/tfar_plugin/functions/fn_aiHearsTFAR.sqf#L77)

**Comment by Neefay** [comment]
Cory, everything about the AI hearing plugin can be just outright removed: the new TFAR already adds that as an in-built function, so it can all be removed.

**Comment by Coryf88** [comment]
@Neefay I'm only finding AI hearing functionality for TFAR Beta in the optional addon "tfar_ai_hearing.pbo"

**Comment by badkneegrow** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/1.0/optionals/ai_hearing/XEH_postInit.sqf#L12
Must be on all clients
